### ISSUE TITLE
Expression animations with Material reference swaps are lost on generated animations

### ISSUE THREAD

**Issue by ocirne23** [hai-vr/combo-gesture-expressions-av3#293]
I have an animation that changes blend shapes and also swaps out a material on the skinned mesh renderer for another.

The blend shapes are fine but the material reference change on the generated zAutogeneratedExp_xxxx_DO_NOT_EDIT animations are lost.

original animation:
![image](https://user-images.githubusercontent.com/1677617/119919464-cc4d7900-bf6a-11eb-9264-f2285e7ae92e.png)

generated animation:
![image](https://user-images.githubusercontent.com/1677617/119919510-e38c6680-bf6a-11eb-815f-d23a03c63dc7.png)

**Comment by hai-vr** [comment]
Thank you for the bug report, a fix is on its way but I will need to test it first.

Since we're at it, this introduces a special case in CGE because a material swap does not have a default value, so in theory, if Write Defaults is OFF, all animations that do not have a material swap defined will continue to use the last used material swap.

There is an undocumented advanced feature called "Fallback Generation". You can put an animation file in there with default values, and these values will be used as the default value when a property is missing from the animation (only when there is at least 1 animation in CGE that animates that property).

I've built the fix so that it can work with fallback generation of material swaps, so if you put a material swap in there, all CGE animations will use that material if it's not defined.

![image](https://user-images.githubusercontent.com/60819407/119970561-2ae91600-bfb0-11eb-8013-266cc88634e1.png)

**Comment by ocirne23** [comment]
I tested the fix (https://github.com/hai-vr/combo-gesture-expressions-av3/tree/i293_ObjectReference),

The generated animations now do have the material reference, and when I preview them, they do show the new material, but when testing (lyuma emulator), it does not apply the material change.

No idea whats going wrong, I tried with an empty FX layer and no other layers/animators active, so nothing should be interfering.

**Comment by hai-vr** [comment]
I haven't had time to test it yet, I think I have an idea why, it's likely the Avatar Mask of the CGE Exp layer.

https://hai-vr.github.io/combo-gesture-expressions-av3/writedefaults#creating-an-avatar-mask-for-the-fx-layer

The CGE Exp on FX layer uses a preset avatar mask that is pretty much *Deny All Transforms*, which will prevent material swaps from functionning.

**Comment by hai-vr** [comment]
Notes to self for testing:

- Risk of regression related to animation generation due to a change in execution order in the animation neutralization process
- Risk of regression which may cause a mutation of user-crafted blend trees due to a change in execution order in the animation neutralization process
- Risk of regression in the general behavior of animators that do not involve avatar masks
