### ISSUE TITLE
EE Property Explorer 'Generate Previews' not working

### ISSUE THREAD

**Issue by jonathanjean** [hai-vr/combo-gesture-expressions-av3#327]
hi! I could not find any discord server of combogesture so I am looking for help here.
I have been using combogesture with no problem thanks! but, sometimes EE property Explorer in Default Editor can generate previews but makes no change in face neverthless Face Blendshapes working fine. I don't know what casue this problem. I think I have made right avatar descriptor, right face not body, and checked pose mode on blender shape key and posture working fine.

And really thank you for making this incredible program I can not imagine make each face gesture animation one by one
![33](https://user-images.githubusercontent.com/28839790/158039251-ac7b25e4-1a78-4de8-a025-a9f7a6f99f92.png)

**Comment by hai-vr** [comment]
Hello, thank you!

This Expressions Editor is about to be removed from ComboGestureExpressions in the near future.
There is already a replacement I've made called Visual Expressions Editor that you can download for free: https://github.com/hai-vr/blendshape-viewer#-visual-expressions-editor

So this issue is likely not going to be fixed as Visual Expressions Editor replaces it.

**Comment by jonathanjean** [comment]
thank you!
