### ISSUE TITLE
Prevent midway eyelids/blink blendshapes by using the VRC Avatar Descriptor to override them back to zero values when generating blink animations

### ISSUE THREAD

**Issue by tomaae** [hai-vr/combo-gesture-expressions-av3#64]
I cannot confirm this is 100% as this is really difficult to reproduce on purpose.
From my observations, issue is as follows:
When blink is triggered for expression and in the middle of blink, expression is changed to one where blink is disabled, eyes wont open from the blink. This result in eyelids closed on 200% (eyelids going through the face), and stay there

I'm just guessing here, but possible solution would be to always allow blink function to open eyes, when they were closed by blink. not only when blink is enabled.

**Comment by hai-vr** [comment]
I would advise trying to modify the animations for the blinking animations so that they override the same blendshapes as the VRC Avatar Descriptor. When eyes tracking are set to Tracking, animations cannot affect the eyes, but when they are set to Animation (which is what the blinking selector does) then the animation can take over those blend shapes.

I don't know if that will fix the issue.

As part of #62 I'm planning to add an optional VRC Avatar Descriptor field to the Compiler so that animations might be auto-generated with overriden blink/eyelids blend shapes and mouth visemes.

**Comment by tomaae** [comment]
Seems to work like that, I just had to delete all mixed experrions and recreate them.
But now (I cant confirm if this was the case before) when I use analog to close eyes (does not have to be full way) and release. blink will be forced right after they are opened.
Sometimes it happens when closing eyes in non-analog way, but I was not able to track when that happenes yet.
